---
title: "chapter"
author: "Sheila"
date: "01/12/2020"
output: html_document
---
## Analysis of longitudinal data

```{r}
# Access the packages dplyr and tidyr
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)

# Read the BPRS and KATS data from folder
BPRSL <- read.table("BPRSL.txt",  header = T)
RATSL <- read.table("RATSL.txt",  header = T)

```

```{r}
summary(BPRSL)
```

```{r}
summary(RATSL)

```

## Look at the data

```{r}
# Take a glimpse at the data
glimpse(BPRSL)
glimpse(RATSL)
```

```{r}
# Look at column name
names(BPRSL)
names(RATSL)
```

```{r}
# Assess the structure
str(BPRSL)
str(RATSL)
```

```{r}
## Analysis of RATSL data
colnames(RATSL) <- c("ID",  "Group" , "WD"  ,   "weight" ,"time")
p1 <- ggplot(RATSL, aes(x=time, y=weight, group=ID)) + geom_line() + facet_grid(.~Group, labeller = label_both)
p1
```
##Fig 8.2 equivalent
```{r}
# Standardize the scores
RATSL <- RATSL %>%
  group_by(time) %>%
  mutate(stdwd = (weight-mean(weight))/sd(weight))%>%
  ungroup()
```

```{r}
glimpse(RATSL)
p2 <- ggplot(RATSL, aes(x=time, y=stdwd, linetype=ID)) + geom_line() + facet_grid(.~Group, labeller = label_both)
p2
```

```{r}
#Fig 8.3 Equivalent
n <- RATSL$time %>% unique() %>% length()
RATSS <- RATSL %>%
  group_by(weight, time) %>%
  summarise(mean=mean(weight), se=sd(weight)/sqrt(n)) %>%
  ungroup()
```

```{r}
#Fig 8.4 Equivalent
p3 <- ggplot(RATSL, aes(x = factor(time), y = weight, fill = Group)) + geom_boxplot(position = position_dodge(width = 0.9))
p3
```

```{r}
# Fig 8.5

RATSL8S <- RATSL %>%
  filter(time > 0) %>%
  group_by(Group, ID) %>%
  summarise( mean=mean(weight) ) %>%
  ungroup()
p4 <- ggplot(RATSL8S, aes(x = Group, y = mean)) + geom_boxplot()
p4
```

```{r}
#Table 8.3
fit <- lm(mean ~ Group, data = RATSL8S)
summary(fit)
anova(fit)
```

```{r}
## Analysis of BPRSL Data
colnames(RATSL) <- c("treatment", "subject" ,  "weeks" ,    "bprs" ,     "week"   )
##Fig 9.1
p5 <- ggplot(RATSL, aes(x = week, y = bprs, group = subject))  + geom_line(aes(linetype = treatment))
p5
```

```{r}
  #Table 9.2
  BPRS_reg <- lm(bprs ~ week + treatment, data = BPRSL)
summary(BPRS_reg)
```

```{r}
#Fig 9.2 
p6 <- ggplot(BPRSL, aes(x = week, y = bprs, group = treatment)) + geom_line(aes(linetype = treatment))
p6
BPRSS <- BPRSL %>%
  group_by(treatment, week) %>%
  summarise( mean=mean(bprs), se=sd(bprs)/sqrt(n) ) %>%
  ungroup()

p7 <- ggplot(BPRSS, aes(x = week, y = mean, linetype = treatment, shape = treatment))+geom_line() + geom_point(size=3) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se, linetype="1"), width=0.3)

p7
```


